# Generated by Django 4.2 on 2023-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='resimler/')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('girisDate', models.DateField()),
                ('cikisDate', models.DateField()),
                ('aciklama', models.TextField(max_length=100)),
                ('fiyat', models.IntegerField()),
                ('resim', models.ManyToManyField(to='card.resim')),
            ],
        ),
    ]
