# Generated by Django 4.2 on 2023-05-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='aciklama',
            field=models.TextField(max_length=1000),
        ),
    ]
