# Generated by Django 4.2 on 2023-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='adress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
