# Generated by Django 4.2 on 2023-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_card_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='puan',
            field=models.IntegerField(default=0),
        ),
    ]
