# Generated by Django 4.2 on 2023-05-15 12:22

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_card_puan'),
    ]

    operations = [
        migrations.AddField(
            model_name='resim',
            name='kendi_eklediginiz_isim',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resim',
            name='resim',
            field=models.ImageField(upload_to=card.models.custom_upload_to),
        ),
    ]
