# Generated by Django 4.2 on 2023-05-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_favori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favori',
        ),
    ]
