# Generated by Django 4.1.5 on 2023-05-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_sepet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banyo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Banyo',
                'verbose_name_plural': 'Banyolar ',
                'db_table': 'banyolar',
            },
        ),
        migrations.CreateModel(
            name='Donanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donanim', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Donanım',
                'verbose_name_plural': 'Donanım',
                'db_table': 'donanimlar',
            },
        ),
        migrations.CreateModel(
            name='Emniyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emniyet', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Emniyet',
                'verbose_name_plural': 'Emniyetler',
                'db_table': 'emniyetler',
            },
        ),
        migrations.CreateModel(
            name='Konum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konum', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Konumlar',
                'verbose_name_plural': 'Konumlar',
                'db_table': 'konumlar',
            },
        ),
        migrations.CreateModel(
            name='Misafir_Girisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misafir_girisi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Misafir Girisi',
                'verbose_name_plural': 'misafir girisi',
                'db_table': 'misafir_girisi',
            },
        ),
        migrations.CreateModel(
            name='Ozellikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozellik', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Özellikler',
                'verbose_name_plural': 'Özellikler',
                'db_table': 'ozellikler',
            },
        ),
        migrations.CreateModel(
            name='TemelOlanaklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olanak', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Temel Olanaklar',
                'verbose_name_plural': 'Temel Olanaklar',
                'db_table': 'temel_olanaklar',
            },
        ),
        migrations.CreateModel(
            name='YatakOdasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yatak_odasi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Yatak Odası',
                'verbose_name_plural': 'yatak odası ',
                'db_table': 'yatak_odasi',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Kartlar', 'verbose_name_plural': 'Kartlar'},
        ),
        migrations.AddField(
            model_name='card',
            name='airbnb_plus',
            field=models.BooleanField(default=False, verbose_name='Airbnb Plus'),
        ),
        migrations.AddField(
            model_name='card',
            name='aninda_rezervasyon',
            field=models.BooleanField(default=False, verbose_name='Anında Rezervasyon'),
        ),
        migrations.AddField(
            model_name='card',
            name='banyo_sayisi',
            field=models.IntegerField(default=0, verbose_name='Banyo Sayısı'),
        ),
        migrations.AddField(
            model_name='card',
            name='kendi_kendi_giris',
            field=models.BooleanField(default=False, verbose_name='Kendi kendine giriş'),
        ),
        migrations.AddField(
            model_name='card',
            name='super_ev_sahibi',
            field=models.BooleanField(default=False, verbose_name='Süper Ev Sahibi'),
        ),
        migrations.AddField(
            model_name='card',
            name='yatak_sayisi',
            field=models.IntegerField(default=0, verbose_name='Yatak Sayısı'),
        ),
        migrations.AddField(
            model_name='card',
            name='yer_tipi',
            field=models.CharField(choices=[('EV', 'Ev'), ('DAIRE', 'Daire'), ('MISAFIR_EVI', 'Misafir Evi'), ('OTEL', 'Otel')], default='EV', max_length=20, verbose_name='Yer Tipi'),
        ),
        migrations.AddField(
            model_name='card',
            name='banyolar',
            field=models.ManyToManyField(to='card.banyo', verbose_name='Banyolar'),
        ),
        migrations.AddField(
            model_name='card',
            name='donanimlar',
            field=models.ManyToManyField(to='card.donanim', verbose_name='Donanımlar'),
        ),
        migrations.AddField(
            model_name='card',
            name='emniyetler',
            field=models.ManyToManyField(to='card.emniyet', verbose_name='Emniyetler'),
        ),
        migrations.AddField(
            model_name='card',
            name='konumlar',
            field=models.ManyToManyField(to='card.konum', verbose_name='Konumlar'),
        ),
        migrations.AddField(
            model_name='card',
            name='misafir_girisi',
            field=models.ManyToManyField(to='card.misafir_girisi', verbose_name='Misafir Girisi'),
        ),
        migrations.AddField(
            model_name='card',
            name='ozellikler',
            field=models.ManyToManyField(to='card.ozellikler', verbose_name='Ozellikler'),
        ),
        migrations.AddField(
            model_name='card',
            name='temel_olanaklar',
            field=models.ManyToManyField(to='card.temelolanaklar', verbose_name='Temel Olanaklar'),
        ),
        migrations.AddField(
            model_name='card',
            name='yatak_odasi',
            field=models.ManyToManyField(to='card.yatakodasi', verbose_name='Yatak Odası'),
        ),
    ]
