# Generated by Django 4.2 on 2023-05-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_card_options_remove_card_airbnb_plus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepet',
            name='card',
        ),
        migrations.RemoveField(
            model_name='sepet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Favori',
        ),
        migrations.DeleteModel(
            name='Sepet',
        ),
    ]
