# Generated by Django 4.2 on 2023-05-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_card_slug_alter_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
    ]
