# Generated by Django 4.2 on 2023-05-29 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0025_rezerve'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='profil',
            field=models.FileField(null=True, upload_to='resimler/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
