# Generated by Django 4.2 on 2023-05-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0026_card_profil_alter_card_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='profil',
        ),
    ]
